// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHsQvIInBnXplAPbxmxc-2nYOi-B8DHkQ',
    appId: '1:795028656452:web:7a9bd7231e7cb501a80711',
    messagingSenderId: '795028656452',
    projectId: 'xenodate',
    authDomain: 'xenodate.firebaseapp.com',
    databaseURL: 'https://xenodate-default-rtdb.firebaseio.com',
    storageBucket: 'xenodate.firebasestorage.app',
    measurementId: 'G-ZY88Q08WM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAwFe1D_qEg8QZDaaAhJelkVuJOokrmo',
    appId: '1:795028656452:android:4e26a019ea67ca53a80711',
    messagingSenderId: '795028656452',
    projectId: 'xenodate',
    databaseURL: 'https://xenodate-default-rtdb.firebaseio.com',
    storageBucket: 'xenodate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCUJsy7E_Wy_VbG6P0nmN9rxb8aSpE27E',
    appId: '1:795028656452:ios:eef2d7ca64b8f6caa80711',
    messagingSenderId: '795028656452',
    projectId: 'xenodate',
    databaseURL: 'https://xenodate-default-rtdb.firebaseio.com',
    storageBucket: 'xenodate.firebasestorage.app',
    iosClientId: '795028656452-ajbfe71sqn1r58cfhol1fs0pt1mmp231.apps.googleusercontent.com',
    iosBundleId: 'noacindustries.com.xenodate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHsQvIInBnXplAPbxmxc-2nYOi-B8DHkQ',
    appId: '1:795028656452:web:0240868910f448c7a80711',
    messagingSenderId: '795028656452',
    projectId: 'xenodate',
    authDomain: 'xenodate.firebaseapp.com',
    databaseURL: 'https://xenodate-default-rtdb.firebaseio.com',
    storageBucket: 'xenodate.firebasestorage.app',
    measurementId: 'G-Z54SBNJC5R',
  );
}
